name: xwrf-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - netcdf4
  - pip
  - pre-commit
  - pytest-cov
  - pytest-sugar
  - wrf-python
  - xarray>=0.18,!=0.20.0,!=0.20.1
  - pip:
      - -r ../requirements.txt
